alter table (rename , edit , add , delete)

diff --git a/DBMS-code b/DBMS-code
--- a/DBMS-code
+++ b/DBMS-code
@@ -422,8 +422,245 @@ function sortTable {
   fi
 tableSelection
 }
+function alterTable {
+  many=$(yad --separator="," --geometry="400x100+100+100"  --title="Alter Table" --entry \
+        --text "options" \
+        --button=gtk-ok:0 \
+          --entry-text \
+    "Rename table" "Add Column" "Edit Column" "Delete Column" )
+case $many in
+      Rename*) renameTable ;;
+    Add*) addCol  ;;
+    Edit*) alter ;;
+    Delete*) delCol ;;
+    *) exit 1 ;;
+esac
+eval exec $cmd
+}
+function renameTable {
+  select_name=$(yad --separator="," --geometry="400x200+100+100"  --title="Rename Table" \
+    --button=gtk-ok:0 \
+     --form \
+    --field="Enter Table Name"
+    )
+tableName=$(echo $select_name | awk 'BEGIN {FS="," } { print $1 }')
+if ! [[ -f $tableName.csv ]]; then
+ yad --text "Table $tableName isn't existed" --geometry="400x200+100+100" --button=gtk-ok:0 --title "Message"
+ tableSelection
+ fi
+ new_name=$(yad --separator="," --geometry="400x200+100+100"  --title="Rename Table" \
+    --button=gtk-ok:0 \
+     --form \
+    --field="Enter new Table Name"
+    )
+    new_tableName=$(echo $new_name | awk 'BEGIN {FS="," } { print $1 }')
+    mv $tableName.csv $new_tableName.csv
+    mv .$tableName .$new_tableName
+        yad --text  "Row updated Successfully" --geometry="400x100+100+100" --button=gtk-ok:0 --title "Message"
+        tableSelection
 
+}
+function alter {
+   table_name=$(yad --separator="," --geometry="400x200+100+100"  --title="Alter Table" \
+    --button=gtk-ok:0 \
+     --form \
+    --field="Enter Table Name"
+    )
+tableName=$(echo $table_name | awk 'BEGIN {FS="," } { print $1 }')
+if ! [[ -f $tableName.csv ]]; then
+ yad --text "Table $tableName isn't existed" --geometry="400x200+100+100" --button=gtk-ok:0 --title "Message"
+ tableSelection
+ fi
+ sep=","
+         rSep="\n"
+  pKey=""
+        unique=""
+        null=""
+  flag=0
+    NR=$(awk 'BEGIN{FS=","}{if ($'3' == "'PK'") print NR}' .$tableName 2>>./.error.log)
 
+    if [[ ( $NR == "" ) ]]; then
+  options=$(yad --separator="," --geometry="400x200+100+100"  --title="Alter Table" \
+   --button=gtk-ok:0 \
+    --form \
+   --field="Enter Condition column name" \
+   --field="Enter new Value to set" \
+   --field="Type of Column ":CB \
+   --field="Make PrimaryKey ?":CB   \
+   --field="Make it Unique? ":CB \
+        --field="Accepts Null? ":CB \
+    "" "" 'Integer!String' 'PK!normal' 'Yes!No' 'Yes!No' 
+   )
+        field=$(echo $options | awk 'BEGIN {FS="," } { print $1 }')
+        newValue=$(echo $options | awk 'BEGIN {FS="," } { print $2 }')
+        colType=$(echo $options | awk 'BEGIN {FS="," } { print $3 }')
+    pKey=$(echo $options | awk 'BEGIN {FS="," } { print $4 }')
+    unique=$(echo $options | awk 'BEGIN {FS="," } { print $5 }')
+    null=$(echo $options | awk 'BEGIN {FS="," } { print $6 }')
+  
+    else
+    many=$(yad --separator="," --geometry="400x200+100+100"  --title="Alter Table" --text="Please enter table stracture:" \
+              --button=gtk-ok:0 \
+               --form \
+              --field="Enter Condition column name" \
+   --field="Enter new Value to set:"  \
+              --field="Type of Column No. $counter":CB \
+    --field="Make it Unique ":CB \
+    --field="Accepts Null? ":CB \
+    "" "" 'Integer!String' 'Yes!No' 'Yes!No' 
+              )
+              field=$(echo $many | awk 'BEGIN {FS="," } { print $1 }')
+  
+        newValue=$(echo $many | awk 'BEGIN {FS="," } { print $2 }')
+
+        colType=$(echo $many | awk 'BEGIN {FS="," } { print $3 }')
+
+                 
+    pKey="normal";
+    unique=$(echo $many | awk 'BEGIN {FS="," } { print $4 }')
+    null=$(echo $many | awk 'BEGIN {FS="," } { print $5 }')
+    
+    fi
+    fid=$(awk 'BEGIN{FS=","}{if(NR==1){for(i=1;i<=NF;i++){if($i=="'$field'") print i}}}' $tableName.csv)
+  if [[ $fid == "" ]]
+  then
+    yad --text  "Field not found" --geometry="400x100+100+100" --button=gtk-ok:0 --title "Message"
+     tableSelection
+ 
+  else
+        sed -i -- 's/'$field'/'$newValue'/g' .$tableName 2>>./.error.log
+        sed -i -- 's/'$field'/'$newValue'/g' $tableName.csv 2>>./.error.log
+
+    
+     if [[ $colType == "Integer" ]]; then
+        if [[ $defvalue =~ ^[0-9]*$ ]]; then
+
+    varr=1;
+         else
+           yad --text "Invalid data type for the default value" --geometry="400x200+100+100" --button=gtk-ok:0 --title "Message"
+    alter
+        fi
+        else
+          if [[ $defvalue =~ ^[a-zA-Z]*$ ]]; then
+    varr=1;
+    else
+     yad --text "Invalid data type for the default value" --geometry="400x200+100+100" --button=gtk-ok:0 --title "Message"
+    alter
+        fi
+      fi
+             NR=$(awk 'BEGIN{FS=","}{if ($'1' == "'$newValue'") print NR}' .$tableName 2>>./.error.log)
+       
+             oldValue=$(awk 'BEGIN{FS=","}{if(NR=='$NR'){for(i=1;i<=NF;i++){if(i=='2') print $i}}}' .$tableName 2>>./.error.log)
+       oldpk=$(awk 'BEGIN{FS=","}{if(NR=='$NR'){for(i=1;i<=NF;i++){if(i=='3') print $i}}}' .$tableName 2>>./.error.log)
+       oldunq=$(awk 'BEGIN{FS=","}{if(NR=='$NR'){for(i=1;i<=NF;i++){if(i=='4') print $i}}}' .$tableName 2>>./.error.log)
+       oldnull=$(awk 'BEGIN{FS=","}{if(NR=='$NR'){for(i=1;i<=NF;i++){if(i=='5') print $i}}}' .$tableName 2>>./.error.log)
+
+             sed -i ''$NR's/'$oldValue'/'$colType'/g' .$tableName 2>>./.error.log
+             sed -i ''$NR's/'$oldpk'/'$pKey'/g' .$tableName 2>>./.error.log
+             sed -i ''$NR's/'$oldunq'/'$unique'/g' .$tableName 2>>./.error.log
+             sed -i ''$NR's/'$oldnull'/'$null'/g' .$tableName 2>>./.error.log
+
+             yad --text "table updated successfully" --geometry="400x200+100+100" --button=gtk-ok:0 --title "Message"
+    
+        tableSelection
+  
+fi
+
+}
+
+function addCol {
+  select_name=$(yad --separator="," --geometry="400x200+100+100"  --title="Delete field" \
+    --button=gtk-ok:0 \
+     --form \
+    --field="Enter Table Name"
+    )
+tableName=$(echo $select_name | awk 'BEGIN {FS="," } { print $1 }')
+if ! [[ -f $tableName.csv ]]; then
+ yad --text "Table $tableName isn't existed" --geometry="400x200+100+100" --button=gtk-ok:0 --title "Message"
+ tableSelection
+ fi
+ NR=$(awk 'BEGIN{FS=","}{if ($'3' == "'PK'") print NR}' .$tableName 2>>./.error.log)
+
+    if [[ ( $NR == "" ) ]]; then
+   many=$(yad --separator="," --geometry="400x200+100+100"  --title="alter Table" --text="Please enter table stracture:" \
+              --button=gtk-ok:0 \
+               --form \
+              --field="Name of Column " \
+              --field="Type of Column ":CB \
+    --field="Make it a primary key? ":CB \
+        --field="Make it Unique? ":CB \
+        --field="Accepts Null? ":CB \
+         --field="Default value " \
+    "" 'Integer!String' 'PK!normal' 'Yes!No' 'Yes!No' ""
+              )
+               colName=$(echo $many | awk 'BEGIN {FS="," } { print $1 }')
+                 colType=$(echo $many | awk 'BEGIN {FS="," } { print $2 }')
+    pKey=$(echo $many | awk 'BEGIN {FS="," } { print $3 }')
+    unique=$(echo $many | awk 'BEGIN {FS="," } { print $4 }')
+    null=$(echo $many | awk 'BEGIN {FS="," } { print $5 }')
+    defvalue=$(echo $many | awk 'BEGIN {FS="," } { print $6 }')
+  else
+     many=$(yad --separator="," --geometry="400x200+100+100"  --title="alter Table" --text="Please enter table stracture:" \
+              --button=gtk-ok:0 \
+               --form \
+              --field="Name of Column " \
+              --field="Type of Column ":CB \
+        --field="Make it Unique? ":CB \
+        --field="Accepts Null? ":CB \
+         --field="Default value " \
+    "" 'Integer!String' 'Yes!No' 'Yes!No' ""
+              )
+               colName=$(echo $many | awk 'BEGIN {FS="," } { print $1 }')
+                 colType=$(echo $many | awk 'BEGIN {FS="," } { print $2 }')
+    pKey='normal';
+    unique=$(echo $many | awk 'BEGIN {FS="," } { print $3 }')
+    null=$(echo $many | awk 'BEGIN {FS="," } { print $4 }')
+    defvalue=$(echo $many | awk 'BEGIN {FS="," } { print $5 }')
+  fi
+  sep=","
+  rsep="\n"
+  echo -e  "$colName$sep$colType$sep$pKey$sep$unique$sep$null$sep$defvalue" >> .$tableName 2>>./.error.log
+  sed -i ''1's/$/'$sep$colName'/' $tableName.csv 2>>./.error.log
+  yad --text "field added" --geometry="400x200+100+100" --button=gtk-ok:0 --title "Message"
+ tableSelection
+
+}
+
+function delCol {
+  select_name=$(yad --separator="," --geometry="400x200+100+100"  --title="Delete field" \
+    --button=gtk-ok:0 \
+     --form \
+    --field="Enter Table Name"
+    )
+tableName=$(echo $select_name | awk 'BEGIN {FS="," } { print $1 }')
+if ! [[ -f $tableName.csv ]]; then
+ yad --text "Table $tableName isn't existed" --geometry="400x200+100+100" --button=gtk-ok:0 --title "Message"
+ tableSelection
+ fi
+options=$(yad --separator="," --geometry="400x200+100+100"  --title="Delete field" \
+  --button=gtk-ok:0 \
+   --form \
+  --field="Enter Condition column name" 
+  )
+field=$(echo $options | awk 'BEGIN {FS="," } { print $1 }')
+
+  fid=$(awk 'BEGIN{FS=","}{if(NR==1){for(i=1;i<=NF;i++){if($i=="'$field'") print i}}}' $tableName.csv)
+  if [[ $fid == "" ]]
+  then
+    yad --text  "Field not found" --geometry="400x100+100+100" --button=gtk-ok:0 --title "Message"
+    tableSelection
+  else
+   
+
+   NR=$(awk 'BEGIN{FS=","}{if ($'1' == "'$field'") print NR}' .$tableName 2>>./.error.log)
+   sed -i 's/[^,]*//'$fid'' $tableName.csv 2>>./.error.log
+   sed -i ''$NR'd' .$tableName 2>>./.error.log
+   sed -i 's/[^,]*,//' $tableName.csv 2>>./.error.log
+ yad --text  "field deleted successfully" --geometry="400x100+100+100" --button=gtk-ok:0 --title "Message"
+    tableSelection
+fi
+
+}
 function Main {
   action=$(yad --geometry="400x100+100+100"  --title "DBMS" --entry  \
   --text "Welcome" \
